name: Aplicação Django

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9

      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true 
        
      - name: Install dependencies
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest 
